leftnav:
- identifier: 3617b6b2-816e-3c48-7c23-b60423a3730f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 95bc12ff-857b-c6b7-5a3a-0c358de9e81c
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a926e84f-f481-bc54-2712-f8a360a38538
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: f23faf2e-2656-38a0-8aad-960f29e0a0a9
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 1be2d5a3-f015-8dfc-1645-5878ba5f19a2
  name: Projects
  pageRef: /pages/projects
  weight: 50
